# Generated by Django 4.1.5 on 2023-01-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='source',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
