# Generated by Django 4.1.5 on 2023-01-26 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_picture_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('difficulty', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
                ('cooktime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredient_picture', to='backend.picture')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('picture_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_picture', to='backend.picture')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_desc', models.TextField()),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_dish', to='backend.dish')),
                ('picture_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipe_picture', to='backend.picture')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientsDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='backend.dish')),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredient', to='backend.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_author', to='backend.user'),
        ),
        migrations.AddField(
            model_name='dish',
            name='picture_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dish_picture', to='backend.picture'),
        ),
    ]
