# Generated by Django 4.1.5 on 2023-01-26 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_dish_ingredient_user_recipestep_ingredientsdishes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture_id',
            field=models.ForeignKey(default='matrix1.png', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_picture', to='backend.picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
